batch_size: 4
batch_size_transfer: 4
learning_rate: 0.0003
learning_rate_transfer: 0.0001
epochs: 1
epochs_transfer: 3
validation_cadence: 2 #How many training sets are gone through per validation set
loss_weights: [0.3,0.7] #For cross entropy loss weighting

#img_dir_first: scanv2/dataset/train-raw
#gt_dir_first: scanv2/dataset/ground-truth 
#img_dir_transfer: images500x500/combine 
#gt_dir_transfer: images500x500/gtCombine 
img_dir_first: scan-v4/train
gt_dir_first: scan-v4/ground-truth
img_dir_transfer: images500x500/combine 
gt_dir_transfer: images500x500/gtCombine 

#img_dir_first: testimages/train_images
#gt_dir_first: testimages/train_masks
#img_dir_transfer: testimages/train_transfer_images
#gt_dir_transfer:  testimages/train_transfer_masks

#img_dir_transfer: testimages/train_images
#gt_dir_transfer: testimages/train_masks
#img_dir_first: testimages/train_transfer_images
#gt_dir_first:  testimages/train_transfer_masks

save_dir: results
validation_fraction: 0.2